### ISSUE TITLE
Lazyload images outside div#content

### ISSUE THREAD

**Issue by cekk** [collective/collective.lazysizes#4]
I'm trying lazysizes on a customer's site where we have some contents with a big header image in a section outside the main content (before it).
The transform doesn't take care about it because it isn't inside the div content.

I think that you start searching images and scripts (in **transformIterable** method) from the div "content" for a reason.
If we extend the lazysizes to all the **body** could it be a problem? Some performance degradation for the transform?

**Comment by hvelarde** [comment]
I tried that at some point just to realize that the perception was worst: content above the fold must be displayed from the very beginning, there's no gain on lazy loading there.

that's why Google PageSpeed Insights recommends to [prioritize visible content](https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent) by avoiding additional network round trips to render the above the fold content of the page.
